name: CI/CD

on:
  push:
    paths:
      - installer/version.txt
  workflow_dispatch:

jobs:
  build:
    name: TMA-1 configuration tool build
    runs-on: windows-latest
    env:
      KIVY_GL_BACKEND: 'angle_sdl2'
        
    steps:
      - uses: actions/checkout@v4.1.1
      - uses: actions/setup-python@v4.7.1
        with: 
          python-version: 3.11
          
      - name: setup Python
        run: |
          python -m pip install --upgrade pip
          pip install -r builder/config/requirements.txt
          pip install pyinstaller
          
      - name: package TMA-1 config tool
        run: |
          pyinstaller builder/main.spec

      - name: cleanup
        shell: cmd
        run: |
          move dist/main.exe builder
          rmdir /S /Q build dist

      - name: zip artifacts
        run: |
          set /p tag=< ./installer/version.txt
          Compress-Archive -Path ./ -Destination monolith-%tag%.zip
          
      - uses: actions/upload-artifact@v3.1.3
        with:
          path: monolith-%tag%.zip